/**
 *
 * these action types, will be used for redux
 */

export const TRANSACTIONS_SELECTED_FILTER = 'TRANSACTIONS_SELECTED_FILTER'

export const TRANSACTIONS_COURIER = 'TRANSACTIONS_COURIER'

export const TRANSACTIONS_PAGINATION = 'TRANSACTIONS_PAGINATION'

export const READ_ALL_TRANSACTIONS = {
  FAILURE: 'READ_ALL_TRANSACTIONS_FAILURE',
  SUCCESS: 'READ_ALL_TRANSACTIONS_SUCCESS',
  REQUEST: 'READ_ALL_TRANSACTIONS_REQUEST',
  CLEAN: 'READ_ALL_TRANSACTIONS_CLEAN',
}
